package cmd

import (
	"fmt"
	"os/exec"
	"strings"

	"github.com/manque-ai/internal"
	"github.com/manque-ai/pkg/ai"
	"github.com/manque-ai/pkg/review"
	"github.com/spf13/cobra"
)

var (
	baseBranch string
	headBranch string
)

var localCmd = &cobra.Command{
	Use:   "local",
	Short: "Run AI review locally on git changes",
	Long:  `Analyzes changes between two git branches (or commits) and outputs an AI review to the terminal.`,
	Run:   runLocalReview,
}

func init() {
	rootCmd.AddCommand(localCmd)
	localCmd.Flags().StringVar(&baseBranch, "base", "main", "Base branch to compare against")
	localCmd.Flags().StringVar(&headBranch, "head", "HEAD", "Head branch (changes source)")
	localCmd.Flags().Bool("mock", false, "Run with mock AI response (for testing UI)")
}

func runLocalReview(cmd *cobra.Command, args []string) {
	// 1. Initialize Logger
	debug, _ := cmd.Flags().GetBool("debug")
	internal.InitLogger(debug)

	// 2. Load Config
	config, err := internal.LoadConfig()
	if err != nil {
		internal.Logger.Error("Failed to load configuration", "error", err)
		return
	}
	
	// For local review, GH_TOKEN is optional
	config.SkipGitHubValidation = true
	if err := config.Validate(); err != nil {
		internal.Logger.Error("Invalid configuration", "error", err)
		return
	}

	// 3. Get Git Diff
	internal.Logger.Info("Getting git diff...", "base", baseBranch, "head", headBranch)
	
	// Check if git is available
	if _, err := exec.LookPath("git"); err != nil {
		internal.Logger.Error("Git not found in PATH")
		return
	}

	// Run git diff
	// Use merge-base to find common ancestor for better diff
	mergeBaseCmd := exec.Command("git", "merge-base", baseBranch, headBranch)
	mergeBaseOut, err := mergeBaseCmd.Output()
	if err != nil {
		internal.Logger.Error("Failed to find merge base. Are branches valid?", "error", err)
		return
	}
	commonAncestor := strings.TrimSpace(string(mergeBaseOut))

	diffCmd := exec.Command("git", "diff", commonAncestor, headBranch)
	diffOut, err := diffCmd.Output()
	if err != nil {
		internal.Logger.Error("Failed to git diff", "error", err)
		return
	}

	diffContent := string(diffOut)
	if len(diffContent) == 0 {
		fmt.Println("No changes detected between branches.")
		return
	}

	internal.Logger.Debug("Diff retrieved", "size", len(diffContent))

	// 3. Init Engine
	// We need to manually construct config or fix the validation issue.
	// Let's Assume LoadConfig succeeded (or we fix it in next step).
	
	engine, err := review.NewEngine(config)
	if err != nil {
		internal.Logger.Error("Failed to initialize engine", "error", err)
		return
	}

	// 4. Run Review
	var summary *ai.PRSummary
	var result *ai.ReviewResult
	
	mock, _ := cmd.Flags().GetBool("mock")
	if mock {
		internal.Logger.Info("Running in MOCK mode...")
		// Use manual PRSummary with fields that match ai/types.go
		summary = &ai.PRSummary{
			Description: "This is a **mock review** generated to demonstrate the terminal output format. In a real run, this would be generated by your chosen LLM.",
			Files: []struct {
				Filename string `json:"filename"`
				Summary  string `json:"summary"`
				Title    string `json:"title"`
			}{
				{Filename: "cmd/local.go", Summary: "Added mock mode for easier local verification and testing."},
				{Filename: "internal/config.go", Summary: "Refactored validation to support optional GitHub tokens."},
			},
		}
		result = &ai.ReviewResult{
			Review: ai.ReviewSummary{
				Score:            95,
				EstimatedEffort:  1,
				HasRelevantTests: true,
				SecurityConcerns: "None detected in this mock run.",
			},
			Comments: []ai.Comment{
				{
					File:      "cmd/local.go",
					StartLine: 80,
					Header:    "💡 Pro Tip",
					Content:   "You can use the --mock flag anytime to verify the output formatting without burning API tokens.",
					Label:     "suggestion",
				},
				{
					File:      "README.md",
					StartLine: 1,
					Header:    "🔴 Documentation Gap",
					Content:   "Consider adding a screenshot of this output to the README to make it even more appealing!",
					Label:     "documentation",
				},
			},
		}
	} else {
		internal.Logger.Info("Analyzing changes... (this may take a minute)")
		var err error
		summary, result, err = engine.Review(diffContent)
		if err != nil {
			internal.Logger.Error("Review extraction failed", "error", err)
			return
		}
	}

	// 5. Output
	output := review.FormatOutput(summary, result)
	fmt.Println("\n" + output)
}
